# Generated by Django 3.0.5 on 2021-04-21 18:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('doctorName', models.CharField(max_length=40, null=True)),
                ('appointmentDate', models.DateField(auto_now=True)),
                ('symptoms', models.CharField(choices=[('fievre chez les enfants,la diarrhée,les vomissements...', 'fievre chez les enfants,la diarrhée,les vomissements..'), ('deficite respiratoire', 'deficite respiratoire'), ("Douleur oculaire violente et subite,Baisse brutale de la vision d'un œil ou de l'autre...", "Baisse brutale de la vision d'un œil ou de l'autre"), ('Anurie,Anérection,Anéjaculation,Azoospermie...', 'Anurie,Anérection,Anéjaculation,Azoospermie...'), ('Hyperactivité,Agitation...', 'Hyperactivité,Agitation...'), ('perte ou prise de poids inexpliquée, fatigue, douleurs, troubles de l’humeur... ', 'perte ou prise de poids inexpliquée, fatigue, douleurs, troubles de l’humeur... '), ("les vomissements,la perte d'appétit,la diarrhée...", "les vomissements,la perte d'appétit,la diarrhée..."), ('Bouton sur le corp,Eruption Cutannee,Rash cutanee...', 'Bouton sur le corp,Eruption Cutannee,Rash cutanee...'), ('Douleur dorsale,Tremblements...', 'Douleur dorsale,Tremblements...'), ('Palpitations ,Sensation de vertige...', 'Palpitations ,Sensation de vertige...'), ('rhume,bouchon de cérumen,angine...', 'rhume,bouchon de cérumen,angine...'), ('mal de dos, rhumatismes, arthrose, fibromylagie...', 'mal de dos, rhumatismes, arthrose, fibromylagie...'), ('Fièvre,maux de tete...', 'Fièvre,maux de tete...')], default='Fièvre,maux de tete...', max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDischargeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40)),
                ('assignedDoctorName', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('admitDate', models.DateField()),
                ('releaseDate', models.DateField()),
                ('daySpent', models.PositiveIntegerField()),
                ('doctorFee', models.PositiveIntegerField()),
                ('OtherCharge', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/PatientProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('admitDate', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/DoctorProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('specialite', models.CharField(choices=[('pediatrie', 'pediatrie'), ('Ophtalmologie', 'Ophtalmologie'), ('Urologie', 'Urologie'), ('Psychiatrie', 'Psychiatrie'), ('Endocrinologie', 'Endocrinologie'), ('Gastro Entérologie', 'Gastro Entérologie'), ('Dermatologie', 'Dermatologie'), ('Neurologie', 'Neurologie'), ('Cardiologie', 'Cardiologie'), ('ORL', 'ORL'), ('medecin-general', 'medecin-general'), ('Rhumatologie ', 'Rhumatologie ')], default='medecin-general', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('Htravail', models.PositiveIntegerField(default=4)),
                ('Occu', models.TimeField(default=datetime.time(8, 0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
