# Generated by Django 3.0.5 on 2021-04-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctorName',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patientName',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='assignedDoctorName',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='patientName',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='symptoms',
        ),
    ]
