# Generated by Django 3.0.5 on 2021-04-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinique', '0002_auto_20210422_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='admitDate',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='daySpent',
        ),
    ]
